version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 28090:80
    environment:
      WORDPRESS_DB_PASSWORD: qwer1011

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer1011
